name: wms
description: A Warehouse Management System for Duroub Sunbulah

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  states_rebuilder: ^5.0.0
  mockito: ^5.0.16
  equatable: ^2.0.3
  font_awesome_flutter: ^9.2.0
  package_info_plus: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  test: ^1.17.10

flutter:

  uses-material-design: true

  assets:
    - assets/activity_logo/
    - assets/fonts/
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: DroidSerif
      fonts:
        - asset: assets/fonts/DroidSerif.ttf